import numpy as np


BOLTZMANN_CONSTANT = 1.380649e-23
ATOMIC_MASS_UNIT = 1.66053906660e-27

ARGON_MASS_KG = 39.948 * ATOMIC_MASS_UNIT
ARGON_SIGMA_METERS = 3.405e-10
ARGON_EPSILON_OVER_KELVIN = 119.8

ARGON_EPSILON_JOULES = (
    ARGON_EPSILON_OVER_KELVIN
    * BOLTZMANN_CONSTANT
)

ARGON_TIME_UNIT_SECONDS = (
    ARGON_SIGMA_METERS
    * np.sqrt(
        ARGON_MASS_KG
        / ARGON_EPSILON_JOULES
    )
)